### ISSUE TITLE
out of memory error when building project

### ISSUE THREAD

**Issue by habdolhay** [Tudat/tudat#337]
Hello,

I updated all the Tudat functions to their latest changes (by pulling and merging Tudat sub module from git) but when I try to build the libraries in Qt I get "cc1plus.exe: out of memory" error specifically when building bytesunitTestEstimationFromIdealDataTimeLongDouble.cpp.obj 
I had no issue beforehand so I suspect I haven't pulled the latest updates properly.
I attached compile output (also the unit test output) in case it can be helpful in identifying the issue.

Cheers,
[Unit Test Output.txt](https://github.com/Tudat/tudat/files/1714298/Unit.Test.Output.txt)
[Compile Output.txt](https://github.com/Tudat/tudat/files/1714299/Compile.Output.txt)

**Comment by DominicDirkx** [comment]
Hi Hamid,

It seems that some of the changes we've made have increased the RAM overhead of the compilation. This will only be the case for specific simulations (in which we use precision greater than double). You can suppress them by setting the COMPILE_HIGH_ACCURACY_ESTIMATION_TESTS to 'OFF' in Projects -> Build -> Cmake, and then clicking the 'Appy configuration changes' button (see below)

![image](https://user-images.githubusercontent.com/5039068/36073430-98f37a5c-0f30-11e8-87f5-dfd435512572.png)

Let me know if this works out,

Dominic

**Comment by habdolhay** [comment]
Hey Dominic, 
Thanks for the help! It seemed to have fixed it. 
The only issue that I face now is when building example applications. I get 
"undefined reference to `tudat::root_finders::doesRootFinderRequireDerivatives(boost::shared_ptr<tudat::root_finders::RootFinderSettings>)'
collect2.exe: error: ld returned 1 exit status"
for satellite propagator example application.
I have also updated the TudatExampleApplication from git (the last commit was from 28 days ago) so not sure where the issue lies.

[Compile Output2.txt](https://github.com/Tudat/tudat/files/1714410/Compile.Output2.txt)

**Comment by DominicDirkx** [comment]
Hi Hamid,

I just saw that the CMakeLists.txt of the example applications was slightly out of date. If you pull the latest version of the example applications (tudat and tudatBundle can remain unchanged), this error should disappear,

Cheers,

Dominic

**Comment by habdolhay** [comment]
Thanks alot! 
The issue is fixed and all example applications are built properly now. Now my own's code give the an exact same compile issue which I think I can fix by updating its CMakelist file

**Comment by habdolhay** [comment]
Everything is fine now. Thanks for the help

**Comment by DominicDirkx** [comment]
Happy to hear it :)

**Comment by DominicDirkx** [comment]
By the way, are the unit tests passing better now? If any still fail, please attach the files listed here:

http://tudat.tudelft.nl/installation/troubleshooting/installationErrors.html#debuggingfailedunittests

So we can figure out what's going wrong.

**Comment by habdolhay** [comment]
Oh good point. There are a number of unit tests failing indeed. I have attached the log files
[LastTest.log](https://github.com/Tudat/tudat/files/1714911/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1714912/LastTestsFailed.log)

**Comment by habdolhay** [comment]
Alright, I managed to identify and fix the errors. 
All of them were related to loading a different SPK file which were fixed when I reverted it back to the default one.  Still, quiet strange that a more complete SPK file would raise issues.

**Comment by DominicDirkx** [comment]
Hi Hamid,

Good to see that you both found and fixed the problem :). 

For my curisosity, which SPK file did you replace with what? There are a few 'custom' SPK files in Tudat, which already consist of several merged (but truncated in time) ephemerides,

Cheers,

Dominic

**Comment by habdolhay** [comment]
Hi Dominic,

In the loadStandardSpiceKernels function, I was loading a merged SPK file (asteroids_and_de430_2.bsp) which was causing the unit test failures. I reverted my modification back to the default one (de430_small.bsp) and it fixed the errors. I also attached a picture for more clarification.

To avoid further problems in the future, I will load a vector of strings to that function instead of tampering with its default settings.
![spice](https://user-images.githubusercontent.com/25635603/36091516-4a822350-0fe4-11e8-8ea6-0ad7d1660442.JPG)

The "asteroids_and_de430_2.bsp" file is a merged one of the two SPK files below (merged in the same order mentioned below)
1. [codes_300ast_20100725.bsp](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/asteroids/) (Asteroids until 2199)
2. [de430.bsp](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/) (until 2650)

.
