### ISSUE TITLE
Error when building PaGMO

### ISSUE THREAD

**Issue by mvandenbroeck** [Tudat/tudat#90]
After I did a 'Build->Clean All' in Qt Creator, I'm getting the following two errors when rebuilding the TudatBundle:

"Unable to locate a c++11 compatible compiler pagmo/CMakeLists.txt:35 (INCLUDE)
C:\tudatBundle_mvdb\pagmo\cmake_scripts\set_compiler_flags.cmake"

and

"[cmake_check_build_system] Error 1"

The error is present even when option(USE_PAGMO ... ) is set to 'OFF' in TudatBundle\CMakeLists.txt.
I heard that it can be caused by a difference in the boost library version between tudat and pagmo. Is there an easy fix to this?

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

For now, comment out the Pagmo includes in the top-level CMakeLists, and continue compiling. I'll get back to you on fixing this,

Dominic

**Comment by mvandenbroeck** [comment]
Hi Dominic,

I'm trying to build and run the main.cpp file in tudatExampleApplications/libraryExamples/PaGMOEx but I get a few thousands of 'undefined reference to ... boost ...' at Linking CXX executables .../pagmo/bin/main.exe
According to this [https://github.com/esa/pagmo/issues/69](url) issue, it has to do with the order of linking. I changed the order around a little bit, but it wouldn't work.

I'm using BoostVersion 1.53.0.
Do you have any ideas that could help me resolve this problem?

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

How exactly did you change the linking order in the CMakeLists? Could you show a 'before' and 'after'?

Another issues might be that your pagmo-boost is compiled differently from your tudat boost. Can you have CMake print the location of the boost libraries (in the pagmo cmake list) and check if it is the same as the Tudat one?

Dominic

**Comment by mvandenbroeck** [comment]
Hi Dominic,

In tudatExampleApplications/PaGMOEx/CMakeLists.txt I changed the following last 4 lines from:

`add_executable(example_library_pagmo "${SRCROOT}/main.cpp")
setup_executable_target(example_library_pagmo "${SRCROOT}")
target_link_libraries( example_library_pagmo  pthread pagmo  my_pagmo_problems
                      tudat_basic_astrodynamics tudat_mission_segments  ${Boost_LIBRARIES} )`

into 

`# Add application.
add_executable(example_library_pagmo "${SRCROOT}/main.cpp")
setup_executable_target(example_library_pagmo "${SRCROOT}")
target_link_libraries( example_library_pagmo  pthread  my_pagmo_problems
                      tudat_basic_astrodynamics tudat_mission_segments pagmo_static ${Boost_LIBRARIES} )

and

`add_executable(example_library_pagmo "${SRCROOT}/main.cpp")
setup_executable_target(example_library_pagmo "${SRCROOT}")
target_link_libraries( example_library_pagmo  pthread   my_pagmo_problems
                      tudat_basic_astrodynamics tudat_mission_segments  ${Boost_LIBRARIES} pagmo )`

For the location of the boost libraries in pagmo/CMakeLists.txt I got: 

optimizedC:/tudatBundle_mvdb/boost/stage/lib/libboost_system-mt.dlldebugC:/tudatBundle_mvdb/boost/stage/lib/libboost_system-mt.aoptimizedC:/tudatBundle_mvdb/boost/stage/lib/libboost_serialization-mt.dlldebugC:/tudatBundle_mvdb/boost/stage/lib/libboost_serialization-mt.aoptimizedC:/tudatBundle_mvdb/boost/stage/lib/libboost_thread-mt.dlldebugC:/tudatBundle_mvdb/boost/stage/lib/libboost_thread-mt.a

For the locatio of the boost libraries in tudatExampleApplications/libraryExamples/PaGMOEx/CMakeLists.txt I got:

C:/tudatBundle_mvdb/boost/stage/lib/libboost_thread-mt.aC:/tudatBundle_mvdb/boost/stage/lib/libboost_date_time-mt.aC:/tudatBundle_mvdb/boost/stage/lib/libboost_system-mt.aC:/tudatBundle_mvdb/boost/stage/lib/libboost_serialization-mt.aC:/tudatBundle_mvdb/boost/stage/lib/libboost_filesystem-mt.aC:/tudatBundle_mvdb/boost/stage/lib/libboost_regex-mt.a

Thanks,

Michael


`

**Comment by DominicDirkx** [comment]
Hi Michael,

I think the problem is that you are changing the wrong CMakeLists. Since the issue is in the linking of the .../pagmo/bin/main.exe executable, you need to change the link order of this executable in:

This is the CMakeLists of pagmo itself, so tudatBundle/pagmo/CMakeLists.txt

Way at the end of the file (line 397 for me) it says:

TARGET_LINK_LIBRARIES(main ${MANDATORY_LIBRARIES} pagmo_static)

Change it to

TARGET_LINK_LIBRARIES(main pagmo_static ${MANDATORY_LIBRARIES})

And with any luck this should fix the issue

**Comment by mvandenbroeck** [comment]
I made the changes you proposed in tudatBundle/pagmo/CMakeLists.txt and also changed the link order in the tudatBundle/pagmo/examples/CMakeLists.txt and tudatBundle/pagmo/tests/CMakeLists.txt. I did a clean rebuild and ran CMake.

Unfortunately it didn't solve the problem, I'm still getting 72k issues of which 1880 are errors of the kind 'undefined reference to ... boost ... '. Apparently the warning suppression didn't work either.
I think I'll pass by your office tomorrow morning again. :-)

I have one more question though. What is the best directory to put the main.cpp file of my personal pagmo optimization? Should I put in tudatBundle/Thesis or tudatBundle/tudatExampleApplications/libraryExamples/PaGMOEx?

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hmmm, could you post some of the full errors in the boost linking?

**Comment by mvandenbroeck** [comment]
Here are some full errors that occur after 
[ 80%] Built target pagmo_static
Linking CXX executable C:\tudatBundle_mvdb\pagmo\bin\main.exe

`C:/tudatBundle_mvdb/pagmo/lib/libpagmo.a(jde.cpp.obj): In function `ZN5boost13serialization16void_cast_detail11void_casterC2EPKNS0_18extended_type_infoES5_iPKS2_':
C:/tudatBundle_mvdb/boost/boost/serialization/void_cast.hpp:143: undefined reference to `_imp___ZTVN5boost13serialization16void_cast_detail11void_casterE'`

`C:/tudatBundle_mvdb/pagmo/lib/libpagmo.a(jde.cpp.obj): In function `ZN5boost7archive6detail19pointer_oserializerINS0_13text_oarchiveEN5pagmo9algorithm3jdeEED1Ev':
C:/tudatBundle_mvdb/boost/boost/archive/detail/oserializer.hpp:223: undefined reference to `_imp___ZN5boost7archive6detail25basic_pointer_oserializerD2Ev'`

`C:/tudatBundle_mvdb/pagmo/lib/libpagmo.a(jde.cpp.obj): In function `ZN5boost7archive6detail11oserializerINS0_13text_oarchiveEN5pagmo9algorithm4baseEEC1Ev':
C:/tudatBundle_mvdb/boost/boost/archive/detail/oserializer.hpp:112: undefined reference to `_imp___ZN5boost7archive6detail17basic_oserializerC2ERKNS_13serialization18extended_type_infoE'`

`C:/tudatBundle_mvdb/pagmo/lib/libpagmo.a(worst_r_policy.cpp.obj): In function `ZN5boost7archive6detail19pointer_oserializerINS0_13text_oarchiveEN5pagmo9migration14worst_r_policyEED2Ev':
C:/tudatBundle_mvdb/boost/boost/archive/detail/oserializer.hpp:223: undefined reference to `_imp___ZN5boost7archive6detail25basic_pointer_oserializerD2Ev'`

The last part of the compile output is:

`C:/tudatBundle_mvdb/pagmo/lib/libpagmo.a(ackley.cpp.obj): In function `ZN5boost7archive6detail21load_non_pointer_typeINS0_13text_iarchiveEE13load_standard6invokeIN5pagmo7problem6ackleyEEEvRS3_RKT_':
C:/tudatBundle_mvdb/boost/boost/archive/detail/iserializer.hpp:387: undefined reference to `_imp___ZN5boost7archive6detail14basic_iarchive11load_objectEPvRKNS1_17basic_iserializerE'
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [C:/tudatBundle_mvdb/pagmo/bin/main.exe] Error 1
mingw32-make[2]: *** [pagmo/CMakeFiles/main.dir/all] Error 2
mingw32-make[1]: *** [pagmo/CMakeFiles/main.dir/rule] Error 2
mingw32-make: *** [main] Error 2
19:34:19: The process "C:\Qt\Tools\mingw491_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop Qt 5.4.1 MinGW 32bit)
When executing step "Make"
19:34:19: Elapsed time: 02:02.`

**Comment by DominicDirkx** [comment]
Hi Michael,

It seems that all the linking errors are in the serialization library, which is not needed by Tudat, but is used by pagmo. Could you check if this library is in the the boost/stage/lib folder?

If it is not, you will need to run CMake again, making sure that the code in add_boost.cmake is not commented out (I think we commented yours out at some point?). If you're not sure about this, just copy the add_boost.cmake (Tudat/External/CMake) from the Tudat repository into your files. Make sure to save the old one just to make sure 

Dominic

**Comment by mvandenbroeck** [comment]
Hi Dominic,

After implementing your feedback and commenting out the applications of which the filenames are too long for Windows, it finally builds!

Thank you for all your help!

Michael

**Comment by DominicDirkx** [comment]
Great!

**Comment by jesperspillenaar** [comment]
Hi Dominic,

My problems seems to be similar. I get thousands of build errors whenever I try to build any of the applications in the tudatBundle/pagmo folder. (The applications 'my_pagmo_problems' and 'pagmo_static' do build).

The errors all have some reference to the serialization library as far as I understand. See for the compile output:

https://github.com/jesperspillenaar/tudatBundle/blob/SpacePlane-develop/questionFiles/Compile%20output

However, in my boost/stage/lib folder I do see the following folder: 'libboost_serialization-mt.a'. Furthermore nothing seems to be commented in the the code in add_boost.cmake.

Any idea how to solve this?

Jesper

**Comment by DominicDirkx** [comment]
Hi Jesper,

Did you try to apply the changes that seemed to work above for Michael. Changing the order of the pagmo link libraries may resolve the issue. If it doesn't, please attach the location of the boost libraries that are being used in the Pagmo CMakeLists,

Dominic

**Comment by jesperspillenaar** [comment]
Hi Dominic,

All changes combined, including swapping the Eigen folder discussed in https://github.com/Tudat/tudat/issues/99 have eventually fixed all errors. Thanks for the help!

Jesper

**Comment by DominicDirkx** [comment]
Great!

**Comment by FrankHogervorst** [comment]
Hi Dominic, 

I've got similar problems. The application in the pagmo folder are working but when I try to build the examples in libraryExamples/PaGMOEx/ i get nearly 1000 errors which all seems to do with serialization. 

I already did the following in the PaGMOEx folder:
- Changed the order of the linking. 
- Changed boost version in all CMakeLists to 1.60 (which I am using)
- Swapped the Eigen folder.
 

Boost libraries used by CMake inside the PaGMOEx folder: 
C:/tudatBundle/boost/stage/lib/libboost_thread-mt.a
C:/tudatBundle/boost/stage/lib/libboost_date_time-mt.a
C:/tudatBundle/boost/stage/lib/libboost_system-mt.a
C:/tudatBundle/boost/stage/lib/libboost_serialization-mt.a
C:/tudatBundle/boost/stage/lib/libboost_filesystem-mt.a
C:/tudatBundle/boost/stage/lib/libboost_regex-mt.a

Boost libraries used by CMake inside the pagmo folder:
C:/tudatBundle/boost/stage/lib/libboost_system-mt.dll;
C:/tudatBundle/boost/stage/lib/libboost_serialization-mt.dll;
C:/tudatBundle/boost/stage/lib/libboost_thread-mt.dll

The CMakeList file: [CMakeLists.txt](https://github.com/Tudat/tudat/files/958402/CMakeLists.txt)
Compile output: [compileoutput.txt](https://github.com/Tudat/tudat/files/958410/compileoutput.txt)

**Comment by DominicDirkx** [comment]
Can you try building the pagmo example? Not the Tudat one, but the main in the Pagmo folder. Does this go correctly?

**Comment by FrankHogervorst** [comment]
That one builts correctly

**Comment by FrankHogervorst** [comment]
The same holds for the examples in the pagmo folder, they do build but I can't run them because of missing dll files.
